### PR TITLE
add ruff and ruff format project

### PR DESCRIPTION
**Pull request by braelyn-ai**
agentstack is starting to scale to the point where we might benefit from consistent formatting.

this PR implements Ruff formatting (no functional code changes) and adds a GitHub workflow pre-merge that verifies code is formatted with Ruff

To format your code:
```bash
pip install ruff
ruff format .
```

### CODE REVIEW

**Comment by bboynton97** [comment]
Open to discussion on if formatting is necessary and if this is how we want to implement it

**Comment by bboynton97** [comment]
ignore quote with

```
ignore = [
    "Q000",  # Single quotes found but double quotes preferred
    "Q001",  # Single quotes found but double quotes preferred (docstring)
    "Q002",  # Single quotes found but double quotes preferred (string)
    "Q003",  # Change outer quotes to avoid escaping inner quotes
]
```

**Comment by bboynton97** [comment]
formatted files but ignored quotes

**Review by tcdent — APPROVED** [review]

**Comment by potpiedev** [comment]
Starting Review, should be available shortly

**Pull request merged**
